"""Manual labels for batch 2 — judgments encoded per job."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
BATCH = ROOT / "_label_batch_2.json"
OUT = ROOT / "_labels_batch_2.jsonl"


def _title(title: str) -> str:
    return (title or "").lower()


def _desc(job: dict) -> str:
    return job.get("description") or ""


# Explicit manual overrides after reading title + description for each job.
# True = include, False = exclude. Keyed by index in batch file.
MANUAL: dict[int, tuple[bool, str]] = {
    # --- DRW (0-39) ---
    0: (False, "Network architect; 3-5 yrs required"),
    1: (False, "Legal counsel; 5+ yrs lawyer"),
    2: (False, "Full-stack SWE; 3-7 yrs required"),
    3: (False, "SWE; 2-10 yrs required"),
    4: (False, "CTO executive role"),
    5: (False, "Macro analyst; finance research not EC SWE"),
    6: (False, "Infra support; 3+ yrs IT required"),
    7: (True, "Research engineer; BS CS, no yrs bar"),
    8: (False, "Network architect; senior role"),
    9: (False, "Surveillance analyst; 3+ yrs finance"),
    10: (False, "Quant researcher; 2+ yrs stat-arb required"),
    11: (False, "Trading SWE; experienced IC, no EC signal"),
    12: (False, "Crypto relationship manager; sales"),
    13: (False, "Trading systems engineer; experienced, no EC bar"),
    14: (False, "Senior SWE; 2+ yrs min but senior title"),
    15: (False, "Platform SWE; 2-3 yrs required"),
    16: (False, "Head of product strategy; leadership"),
    17: (False, "SWE tools; 2+ yrs minimum"),
    18: (False, "Senior platform engineer"),
    19: (False, "AI engineer; 3+ yrs ML required"),
    20: (True, "Trading systems engineer; 1-3 yrs, internships count"),
    21: (False, "Quant trading analyst; finance not EC tech"),
    22: (False, "SWE tools; 2+ yrs minimum"),
    23: (False, "University talent acquisition; HR"),
    24: (False, "Research SWE; experienced, $175-225k band"),
    25: (False, "Data engineer; 3+ yrs pipelines"),
    26: (False, "SWE tools; 2+ yrs minimum"),
    27: (False, "FICC relationship manager; sales"),
    28: (False, "Quant developer; 3+ yrs required"),
    29: (False, "Prediction markets SWE; 2+ yrs"),
    30: (False, "Quant dev stat-arb; 3+ yrs required"),
    31: (False, "Python SWE trading; 3+ yrs required"),
    32: (False, "Talent operations coordinator; HR"),
    33: (False, "SWE tools; 2+ yrs minimum"),
    34: (False, "Senior SWE trading GUI"),
    35: (False, "University talent acquisition; HR"),
    36: (False, "Senior associate middle office; finance ops"),
    37: (False, "Desktop systems engineer; experienced support"),
    38: (False, "Senior data engineer"),
    39: (False, "Senior SWE; 5+ yrs required"),
    # --- Cohere (40-139) ---
    40: (False, "Data infra SWE; senior experience"),
    41: (False, "Product manager; non-engineering"),
    42: (False, "Solutions architect; senior presales"),
    43: (False, "Director SEC reporting; finance"),
    44: (False, "Search apps SWE; production exp, no EC bar"),
    45: (False, "Head of solutions architecture; 10+ yrs"),
    46: (False, "Customer success manager; non-tech"),
    47: (False, "FDE infra; enterprise deployment exp required"),
    48: (False, "Data annotation specialist; contractor ops"),
    49: (False, "FDE infra Japan; experienced deployment"),
    50: (False, "Technical program manager; management"),
    51: (False, "Engineering manager"),
    52: (False, "Technical revenue manager; finance"),
    53: (False, "Director infrastructure finance"),
    54: (False, "FDE agentic; production Python exp required"),
    55: (False, "MTS data evaluation; experienced IC"),
    56: (False, "MTS agents modeling; experienced IC"),
    57: (False, "Strategic account executive; sales"),
    58: (False, "SWE Collect; mentors juniors, experienced hire"),
    59: (False, "MTS integration/RL; experienced IC"),
    60: (False, "MTS MLE Korea; experienced IC"),
    61: (False, "Senior SWE agent infrastructure"),
    62: (False, "MTS MLE UK/EU; experienced IC"),
    63: (False, "Data annotation Arabic; language ops"),
    64: (False, "Manager of technical staff; management"),
    65: (False, "EM FDE infrastructure EMEA"),
    66: (False, "Finance PMO; non-engineering"),
    67: (False, "Manager real estate & facilities"),
    68: (False, "Data annotation Arabic dialect; ops"),
    69: (False, "FDE infra UK/EU; experienced K8s admin"),
    70: (False, "FDE agentic UK; production RAG exp"),
    71: (False, "Senior accountant; finance"),
    72: (False, "Customer marketing manager"),
    73: (False, "IT operations specialist; support role"),
    74: (False, "Engineering manager agentic platform"),
    75: (False, "Senior research scientist evaluation"),
    76: (False, "Business operations lead"),
    77: (False, "MTS sovereign AI; experienced IC"),
    78: (True, "Research internship Fall 2026; ML/NLP PhD track"),
    79: (False, "MTS MLE North; experienced IC"),
    80: (False, "Full-stack inference SWE; 5+ yrs"),
    81: (False, "MTS safety for agents; experienced IC"),
    82: (False, "Senior MTS multimodal AI"),
    83: (False, "Solutions marketing manager"),
    84: (False, "Senior manager revenue ops; 10+ yrs"),
    85: (False, "Senior counsel commercial; legal"),
    86: (False, "Applied ML UK public sector; 8+ yrs SC clearance"),
    87: (False, "Staff SWE inference infrastructure"),
    88: (False, "Senior security engineer"),
    89: (False, "MTS post-training; experienced IC not fellowship"),
    90: (False, "Senior/staff full-stack engineer"),
    91: (False, "FDE agentic Middle East; production exp"),
    92: (False, "Senior SWE security agents"),
    93: (False, "VP Sales EMEA"),
    94: (False, "FDE sovereign AI; production exp"),
    95: (False, "Lead MTS inference; experienced IC"),
    96: (False, "Senior ML systems engineer"),
    97: (False, "FDE prompt specialist; customer-facing exp"),
    98: (False, "Senior financial analyst"),
    99: (False, "Staff SWE GPU infrastructure HPC"),
    100: (False, "MTS agent code; experienced IC"),
    101: (False, "Senior account executive public sector"),
    102: (False, "MTS pre-training data; experienced IC"),
    103: (False, "FDE infra public sector; experienced"),
    104: (False, "Senior HR business partner"),
    105: (False, "Staff research engineer model efficiency"),
    106: (False, "Data annotation German; language ops"),
    107: (False, "Senior account executive energy"),
    108: (False, "Senior research scientist Cohere Labs"),
    109: (False, "Applied AI engineer agentic; substantial production exp"),
    110: (False, "GRC specialist; compliance not engineering"),
    111: (False, "Senior security operations engineer"),
    112: (False, "Lead data scientist; leadership"),
    113: (False, "Talent acquisition partner; recruiting"),
    114: (False, "FDE infra Dubai; 3+ yrs deployment"),
    115: (False, "Security operations manager; 8+ yrs"),
    116: (True, "Software engineer intern Fall/Winter 2026"),
    117: (True, "ML intern/co-op Fall 2026"),
    118: (False, "Product marketing manager"),
    119: (False, "MTS search; experienced IC"),
    120: (False, "SWE security; senior experience"),
    121: (False, "Recruitment coordinator; HR"),
    122: (False, "Chief of staff; 10+ yrs strategy"),
    123: (False, "Senior solutions architect"),
    124: (False, "SRE inference; senior experience"),
    125: (False, "Research engineer; experienced IC, no EC bar"),
    126: (False, "TPM north delivery; management"),
    127: (False, "Strategic account executive telecom"),
    128: (False, "Partner marketing manager"),
    129: (False, "Internal communications manager"),
    130: (False, "Sales development intern; non-tech sales"),
    131: (False, "Senior manager inside sales"),
    132: (False, "MTS training infra; experienced IC"),
    133: (False, "MTS MLE; experienced IC"),
    134: (False, "Senior manager FP&A"),
    135: (False, "Solutions architect public sector Ottawa"),
    136: (False, "Senior research engineer model evaluation"),
    137: (False, "Applied AI engineer Korea; team lead level"),
    138: (False, "Data annotation Portuguese; ops"),
    139: (False, "Product manager native experience"),
    # --- Point72 (140-239) ---
    140: (True, "ML engineer; PhD candidate, research ML/NLP"),
    141: (False, "Mobility endpoint engineering; IT support India"),
    142: (False, "Cubist portfolio manager; 10+ yrs"),
    143: (False, "Academy investment analyst; finance not tech"),
    144: (False, "NLP engineer; 3+ yrs NLP required"),
    145: (False, "Cubist quant researcher; 2+ yrs equities research"),
    146: (False, "HR associate compensation; non-tech"),
    147: (False, "Recruiter"),
    148: (False, "AI validation engineer; senior QA automation"),
    149: (False, "Tax associate PE/VC; finance"),
    150: (True, "Data scientist; BS/MS/PhD quant, no yrs bar"),
    151: (False, "Cubist data scientist; Masters, experienced"),
    152: (False, "Corporate access associate; finance"),
    153: (False, "Research tech support; 2+ yrs support"),
    154: (False, "Fundamental researcher; finance research"),
    155: (False, "Cubist portfolio manager; 10+ yrs"),
    156: (False, "Identity governance analyst; security ops"),
    157: (False, "Ubuntu Linux engineer; IT India"),
    158: (False, "Service desk engineer; IT support"),
    159: (False, "Academy investment analyst 2027; finance program"),
    160: (False, "Systems analyst financial technology"),
    161: (False, "Macro quant researcher; 4+ yrs signal research"),
    162: (False, "Senior data engineer proprietary research"),
    163: (False, "Senior Java SWE macro middle office"),
    164: (False, "Trader; 2+ yrs algo trading"),
    165: (True, "Quantitative researcher intern"),
    166: (False, "Academy investment analyst Singapore; finance"),
    167: (False, "SWE fund admin tech; experienced"),
    168: (False, "SRE India; experienced platform"),
    169: (False, "Cubist senior data scientist; 5+ yrs"),
    170: (False, "Service desk engineer; IT support"),
    171: (False, "Academy investment analyst Hong Kong; finance"),
    172: (False, "SWE execution services; senior experience"),
    173: (False, "Quantitative researcher; MSc/PhD experienced"),
    174: (False, "Data engineer knowledge graph; senior"),
    175: (False, "Cubist quant researcher; experienced research"),
    176: (False, "Associate general counsel tax; legal"),
    177: (False, "DevOps engineer Mi-Platform; experienced"),
    178: (False, "GenAI security engineer; senior"),
    179: (False, "Academy investment analyst Japan; finance"),
    180: (False, "Trader/quant analyst; 3+ yrs convertible bonds"),
    181: (False, "Quantitative researcher Taiwan; PhD candidates ok but research IC"),
    182: (False, "Salesforce engineer; experienced"),
    183: (False, "Quant analyst/SWE; 1-3 yrs (upper bound 3+)"),
    184: (False, "Equity financing trader; finance"),
    185: (False, "Credit analyst; finance"),
    186: (False, "Mission control specialist; ops NOC not EC engineering"),
    187: (False, "Cubist senior data scientist Singapore; 5+ yrs"),
    188: (False, "IT ops engineer app support; experienced"),
    189: (False, "SWE middle office AI/ML; 3+ yrs markets tech"),
    190: (False, "Head of compliance Hong Kong"),
    191: (False, "Security engineer detection; senior"),
    192: (False, "Support engineer macro technology"),
    193: (False, "Central funding application delivery manager"),
    194: (False, "Quant developer CIO office; senior $175-300k"),
    195: (False, "Cubist quant researcher multi-location; experienced"),
    196: (False, "Employee relations specialist; HR"),
    197: (False, "IT operation engineer research; experienced"),
    198: (False, "SWE data platform Warsaw; experienced"),
    199: (False, "Treasury technology; 8+ yrs C#/.NET"),
    200: (False, "Sector analyst MI-Data; finance research"),
    201: (False, "App support engineer 3; experienced support"),
    202: (False, "Senior SDLC engineer India"),
    203: (False, "Associate equity valuation PnL; finance ops"),
    204: (False, "PM administrative assistant"),
    205: (False, "Analyst coach investment development; finance"),
    206: (False, "Manager India finance"),
    207: (False, "International sector analyst MI-Data"),
    208: (False, "Quant researcher; 3+ yrs systematic alpha"),
    209: (False, "Investor relations coordinator"),
    210: (False, "Business analyst Singapore; 2+ yrs preferred"),
    211: (False, "Cubist portfolio manager multi-location"),
    212: (False, "Project manager back office ops"),
    213: (False, "Systems analyst Workday HCM; experienced"),
    214: (True, "Quantitative developer intern"),
    215: (False, "Quant finance researcher Taiwan; PhD research IC"),
    216: (True, "Data scientist; BS/MS/PhD quant, no yrs bar"),
    217: (False, "Fundamental researcher Canvas; finance"),
    218: (False, "Administrative assistant"),
    219: (False, "Market data solutions specialist"),
    220: (False, "Sector analyst proprietary research"),
    221: (False, "Data sourcing strategy ops analyst"),
    222: (False, "Product strategist L/S equities; finance"),
    223: (False, "Investment analyst summer intern; finance not tech"),
    224: (False, "ML infra engineer GenAI; experienced"),
    225: (False, "Finance summer intern Warsaw; non-tech finance"),
    226: (False, "Data reliability engineer; 3+ yrs support"),
    227: (False, "AI engineer IS; 5+ yrs required"),
    228: (False, "NLP engineer; experienced NLP/LLM"),
    229: (False, "HR analyst Japan; 3+ yrs HR"),
    230: (False, "Power & gas trading risk manager"),
    231: (False, "Microstructure quant researcher; 4+ yrs"),
    232: (False, "Knowledge engineer; senior"),
    233: (False, "Cubist business analyst; 2 yrs plus preferred"),
    234: (False, "Regulatory reporting senior associate"),
    235: (False, "Senior .NET SWE macro middle office"),
    236: (False, "Quant researcher trading research; 2+ yrs minimum"),
    237: (False, "Backend engineer Warsaw; senior"),
    238: (False, "Analyst coach Singapore; finance"),
    239: (False, "Academy insight program Japan; finance"),
    # --- Cognition AI (240-298) ---
    240: (False, "Special projects engineer; 2+ yrs or founder exp"),
    241: (False, "General application; open pool"),
    242: (False, "Research post-training; frontier MTS not EC"),
    243: (False, "HR operations recruiter coordinator; HR"),
    244: (False, "Deployed engineer; enterprise GTM, experienced"),
    245: (False, "Engagement manager; enterprise leadership"),
    246: (False, "Head of partnerships APAC"),
    247: (False, "Product marketer"),
    248: (False, "Product engineer; frontier AI lab experience"),
    249: (False, "AI support engineer; senior support"),
    250: (False, "Special projects engineer Europe; 2+ yrs"),
    251: (False, "Deployed engineer Europe; enterprise GTM"),
    252: (False, "Commercial counsel; legal 7+ yrs"),
    253: (False, "Software engineer; frontier AI lab experience"),
    254: (False, "Sales development representative"),
    255: (False, "AI enablement engineer; senior enablement"),
    256: (False, "Deployed engineer APAC Tokyo; enterprise deployments"),
    257: (False, "Data engineer; senior data/BI"),
    258: (False, "Revenue operations; 4+ yrs RevOps"),
    259: (False, "IT engineer; IT support"),
    260: (False, "Partner marketer"),
    261: (False, "Partner deployed engineer APAC India"),
    262: (False, "Account based marketer; 2-4 yrs marketing"),
    263: (False, "Account director enterprise; sales"),
    264: (False, "Federal account executive; sales"),
    265: (False, "Business operations; 3-5 yrs consulting/ops"),
    266: (False, "Deployed engineer federal; gov experience"),
    267: (False, "Account director; enterprise sales"),
    268: (False, "Account director Europe; sales"),
    269: (False, "Director enterprise sales Central"),
    270: (False, "Director enterprise sales West"),
    271: (False, "Partner deployed engineer APAC Tokyo"),
    272: (False, "Partner deployed engineer Europe"),
    273: (False, "Partner deployed engineer"),
    274: (False, "Sales development representative London"),
    275: (False, "DevOps engineer federal; experienced"),
    276: (False, "Account director Europe DACH; sales"),
    277: (False, "Commercial counsel Europe; legal"),
    278: (False, "Account manager enterprise; customer-facing sales"),
    279: (False, "Brand marketer"),
    280: (False, "Deployed engineer APAC Singapore; enterprise"),
    281: (False, "QA engineer APAC; senior QA"),
    282: (False, "Senior accountant; finance"),
    283: (False, "Partner director; partnerships leadership"),
    284: (False, "Developer community manager; marketing"),
    285: (False, "Account director ANZ; sales"),
    286: (False, "Technical engagement manager federal; senior"),
    287: (False, "Paid media marketer"),
    288: (False, "Account director APAC Tokyo; sales"),
    289: (False, "Deployed engineer ANZ; enterprise deployments"),
    290: (False, "Research engineer infrastructure; senior GPU/ML systems"),
    291: (False, "Forward deployed marketer"),
    292: (False, "Strategic AI analyst; 4+ yrs finance/consulting"),
    293: (False, "SRE; experienced platform"),
    294: (False, "Research mid-training; frontier research IC"),
    295: (False, "Account director MENA; sales"),
    296: (False, "Security engineer; senior $260-300k"),
    297: (False, "Account director APAC Singapore; sales"),
    298: (False, "Deployed engineer LATAM; enterprise GTM"),
    # --- Together AI (299-353) ---
    299: (False, "AI infrastructure engineer; 5+ yrs"),
    300: (False, "AI infra SRE Amsterdam; 7+ yrs"),
    301: (False, "AI researcher core ML; senior research"),
    302: (True, "Analytics engineer data warehouse; 0-4 yrs"),
    303: (True, "Backend SWE data platform; 0-4 yrs"),
    304: (False, "Customer support engineer GPU; 3+ yrs"),
    305: (False, "Customer support engineer GPU India; 3+ yrs"),
    306: (False, "Customer support engineer inference India; 5+ yrs"),
    307: (True, "Data warehouse engineer; 0-4 yrs"),
    308: (False, "Director data center operations"),
    309: (False, "Director of tax"),
    310: (False, "Engineering manager tech lead; 8+ yrs"),
    311: (False, "Finance analytics engineer; 5+ yrs"),
    312: (False, "FDE GPU clusters; 5+ yrs"),
    313: (False, "FDE inference post-training; 5+ yrs"),
    314: (False, "Infrastructure accounting manager"),
    315: (False, "Infrastructure design engineer; 7+ yrs"),
    316: (False, "Infrastructure vendor ops manager"),
    317: (False, "IT engineer Amsterdam; experienced admin"),
    318: (False, "Junior TPM infra ops; TPM not engineering IC"),
    319: (False, "Lead product designer; 7+ yrs"),
    320: (False, "LLM inference frameworks engineer; 3+ yrs"),
    321: (False, "ML engineer; 5+ yrs"),
    322: (False, "ML engineer inference; 3+ yrs"),
    323: (False, "ML platform engineer; 5+ yrs"),
    324: (False, "Payroll manager"),
    325: (False, "Product marketing director"),
    326: (False, "Research engineer core ML; senior"),
    327: (False, "Research engineer speculative decoding; experienced"),
    328: (False, "Sales and marketing ops manager"),
    329: (False, "Senior backend engineer inference"),
    330: (False, "Senior data engineer"),
    331: (False, "Senior developer productivity engineer"),
    332: (False, "Senior ML engineer voice AI"),
    333: (False, "Senior network engineer; 8+ yrs"),
    334: (False, "Senior platform engineer voice AI"),
    335: (False, "Senior program manager data center"),
    336: (False, "Senior SWE together cloud infrastructure"),
    337: (False, "Senior SWE together cloud platform"),
    338: (False, "Senior technical recruiter"),
    339: (False, "Solutions architect; 5+ yrs presales"),
    340: (False, "Sr partnerships manager model ecosystem"),
    341: (False, "Sr revenue accountant"),
    342: (False, "Sr TPM; 5+ yrs ML infra"),
    343: (False, "Staff backend engineer commerce"),
    344: (False, "Staff engineer API core platform"),
    345: (False, "Staff engineer customer insights"),
    346: (False, "Staff engineer distributed storage HPC"),
    347: (False, "Staff engineer product UI platform"),
    348: (False, "Staff ML engineer voice AI"),
    349: (False, "Staff platform engineer voice AI"),
    350: (False, "Strategic finance senior manager"),
    351: (False, "Systems research engineer GPU; experienced"),
    352: (False, "Technical account manager AI factory; 5+ yrs"),
    353: (False, "Together cloud infrastructure engineer; 5+ yrs"),
    # --- Sierra (354-453) ---
    354: (False, "Enterprise sales leader ANZ"),
    355: (False, "SWE agent Paris; experienced FDE-style"),
    356: (False, "Brand designer contract; design"),
    357: (False, "Product manager agent development; PM"),
    358: (False, "SWE agent Korean; experienced customer-facing"),
    359: (False, "Forward deployed infra engineer; experienced"),
    360: (False, "SWE agent data platform; large-scale data exp"),
    361: (False, "GTM operations agent development"),
    362: (False, "Operations manager product & engineering"),
    363: (False, "People operations; HR"),
    364: (False, "Product manager agent studio"),
    365: (False, "Communications manager"),
    366: (False, "PM agent development Italian"),
    367: (False, "Developer relations engineer; senior DevRel"),
    368: (False, "Executive assistant"),
    369: (False, "Enterprise account executive German"),
    370: (False, "University recruiter; HR"),
    371: (False, "Sales engineer French"),
    372: (False, "PM agent development Tokyo"),
    373: (False, "Strategist agent development Arabic; GTM not SWE"),
    374: (False, "Support engineer; customer support"),
    375: (False, "SWE identity & enterprise platform; experienced"),
    376: (False, "SWE agent Spanish; experienced FDE"),
    377: (False, "Enterprise account executive Tokyo"),
    378: (False, "Agent experience designer voice; senior design"),
    379: (False, "SWE voice; senior experience"),
    380: (False, "Sales director"),
    381: (False, "SWE agent Tokyo; experienced"),
    382: (False, "Agent experience designer voice multilingual"),
    383: (False, "Business development"),
    384: (False, "Product designer"),
    385: (False, "SWE agent Munich; experienced"),
    386: (False, "Enterprise sales leader Paris"),
    387: (False, "Recruiting operations specialist; HR"),
    388: (False, "SWE frontend; proven production track record"),
    389: (False, "PM agent development healthcare"),
    390: (False, "PM agent development London"),
    391: (False, "PM voice"),
    392: (True, "Intern agent development Fall 2026"),
    393: (False, "SWE agent SF; experienced customer-facing"),
    394: (False, "Strategist agent development French; GTM"),
    395: (False, "Security and compliance manager"),
    396: (False, "Global benefits manager; HR"),
    397: (False, "SWE insights; senior data/analytics"),
    398: (False, "Commercial counsel; legal"),
    399: (False, "GTM strategy & operations"),
    400: (False, "Security TPM; senior program mgmt"),
    401: (False, "SWE infrastructure; senior experience"),
    402: (False, "GTM engineer; Salesforce/custom integrations"),
    403: (False, "Sales engineer Tokyo"),
    404: (False, "SWE agent Singapore; experienced"),
    405: (False, "SWE agent Sydney; experienced"),
    406: (False, "Office manager contractor"),
    407: (False, "Commercial counsel Atlanta; legal"),
    408: (False, "SWE product; senior experience"),
    409: (False, "PM agent development Spanish"),
    410: (False, "Strategist agent development financial services; GTM"),
    411: (False, "SWE agent builder; senior"),
    412: (False, "PM agent SDK; senior PM"),
    413: (False, "Office manager London"),
    414: (False, "Strategist agent development French Paris"),
    415: (False, "Enterprise account executive Italian"),
    416: (False, "GTM operations agent development NYC"),
    417: (False, "Strategist agent development Munich"),
    418: (False, "SWE agent Cantonese Singapore"),
    419: (False, "Sales engineer SF"),
    420: (False, "SWE agent Madrid"),
    421: (False, "SWE agent Arabic London"),
    422: (False, "Security compliance manager London"),
    423: (False, "Security engineer; experienced"),
    424: (False, "Enterprise account executive Arabic"),
    425: (False, "Strategist agent development Cantonese"),
    426: (False, "SWE agent German London"),
    427: (False, "Strategist agent development Spanish Madrid"),
    428: (False, "Enterprise sales leader US remote"),
    429: (False, "PM agent development Arabic"),
    430: (False, "Enterprise account executive ANZ"),
    431: (False, "PM agent development French London"),
    432: (False, "SWE agent London; experienced"),
    433: (False, "Corporate security engineer lead"),
    434: (False, "Sales engineer Spain"),
    435: (False, "SWE agent healthcare; experienced FDE"),
    436: (False, "SWE platform; senior experience"),
    437: (False, "PM agent development Singapore"),
    438: (False, "SWE agent Toronto; experienced"),
    439: (False, "PM agent data platform"),
    440: (False, "Presentation designer"),
    441: (False, "Senior legal counsel Tokyo"),
    442: (False, "Strategist agent development healthcare; GTM"),
    443: (False, "Strategist agent development SF; GTM"),
    444: (False, "Strategist agent development Tokyo; GTM/consulting"),
    445: (False, "Strategist agent development Singapore"),
    446: (False, "Strategist agent development Spanish London"),
    447: (False, "Sales engineer Munich"),
    448: (False, "Developer relations engineer SF; senior"),
    449: (False, "SWE agent architecture; senior"),
    450: (False, "SWE SRE; senior experience"),
    451: (False, "SWE security; experienced security IC"),
    452: (False, "PM ghostwriter"),
    453: (False, "Strategist agent development Sydney"),
    # --- Runway ML (454-487) ---
    454: (False, "Senior accountant"),
    455: (False, "Staff product analytics engineer"),
    456: (False, "MTS backend engineer API; experienced IC"),
    457: (False, "MTS research engineer GPU; experienced IC"),
    458: (False, "Research science manager; management"),
    459: (False, "MTS applied research scientist; experienced IC"),
    460: (False, "Senior/staff technical recruiter"),
    461: (False, "MTS research engineer datasets; experienced IC"),
    462: (False, "Creative support specialist; non-tech support"),
    463: (False, "AI engagement manager; customer success"),
    464: (False, "Enterprise account executive"),
    465: (False, "Engineering manager API"),
    466: (False, "API deployment manager"),
    467: (False, "MTS research engineer; experienced IC"),
    468: (False, "Senior/staff business/creative recruiter"),
    469: (False, "Design engineer; experienced design+code"),
    470: (False, "Staff product manager ML research"),
    471: (False, "Creative support specialist enterprise"),
    472: (False, "Creative workflow architect"),
    473: (False, "Sr/staff product designer"),
    474: (False, "Member of partnerships staff physical AI"),
    475: (False, "B2B marketing director"),
    476: (False, "Copywriter"),
    477: (False, "Creative director"),
    478: (False, "Art director"),
    479: (False, "General manager Japan"),
    480: (False, "Counsel/senior counsel litigation"),
    481: (False, "MTS mobile engineer; 5+ yrs mobile"),
    482: (False, "MTS developer relations lead"),
    483: (False, "Enterprise account executive London"),
    484: (False, "Commercial counsel; legal"),
    485: (False, "Member of partnerships staff"),
    486: (False, "Corporate development; finance/M&A"),
    487: (False, "Sr manager sales development"),
    # --- CoreWeave (488-587) ---
    488: (False, "Manager energy & power transaction; finance"),
    489: (False, "Director global people operations; HR"),
    490: (False, "Senior manager corporate development accounting"),
    491: (False, "Senior cloud support engineer"),
    492: (False, "Senior engineer storage control plane"),
    493: (False, "Staff business systems engineer; 10+ yrs NetSuite"),
    494: (False, "Principal engineer observability"),
    495: (False, "Head of market intelligence"),
    496: (False, "Senior benefits manager; HR"),
    497: (False, "Senior revenue accountant"),
    498: (False, "Security operations engineer; experienced"),
    499: (False, "Senior SWE observability"),
    500: (False, "Staff product manager insights"),
    501: (False, "Senior PM data center; 8+ yrs"),
    502: (False, "Staff data center augmentation engineer"),
    503: (False, "Infrastructure ops program manager"),
    504: (False, "Executive assistant IT"),
    505: (False, "Command center systems engineer; senior"),
    506: (False, "Technical project manager east region"),
    507: (False, "Senior security engineer PKI"),
    508: (False, "Staff engineer Cilium CNI"),
    509: (False, "Integration engineer people technologies"),
    510: (False, "Manager technical recruiting; HR"),
    511: (False, "Staff thermal engineer; 10+ yrs"),
    512: (False, "Senior data scientist forecasting"),
    513: (False, "Staff business systems engineer data center"),
    514: (False, "Solutions architect HPC/AI/ML; senior presales"),
    515: (False, "Command center ops governance specialist"),
    516: (False, "Product manager finance"),
    517: (False, "SWE observability; experienced (non-senior title but no EC bar visible)"),
    518: (False, "Senior electrical engineer"),
    519: (False, "Senior business systems engineer supply chain"),
    520: (False, "Senior SWE molab"),
    521: (False, "Accounting manager capital assets"),
    522: (False, "Senior production engineer; 7+ yrs"),
    523: (False, "Operations engineering manager fleet reliability"),
    524: (False, "Senior manager data infrastructure services"),
    525: (False, "Senior enterprise account executive UK"),
    526: (False, "Staff SWE observability"),
    527: (False, "Data center OFCI quality manager"),
    528: (False, "Staff production engineer"),
    529: (False, "Staff security engineer vulnerability mgmt"),
    530: (False, "Senior SWE data center infra tooling"),
    531: (False, "Senior SWE server fleet infrastructure; 5+ yrs"),
    532: (False, "Staff frontend engineer DC infra"),
    533: (False, "Solutions architect; senior presales"),
    534: (False, "Staff systems engineer architect"),
    535: (False, "Data center manager; operations leadership"),
    536: (False, "Senior associate energy market development"),
    537: (False, "Sr SWE source control governance"),
    538: (False, "Senior manager accounting transformation; 10+ yrs"),
    539: (False, "Offensive security engineer; senior"),
    540: (False, "Senior production engineer Singapore; 7+ yrs"),
    541: (False, "Solutions architect Kubernetes Singapore"),
    542: (False, "Solutions architect networking"),
    543: (False, "Solutions architect Kubernetes"),
    544: (False, "SDR; sales development"),
    545: (False, "Director field enablement"),
    546: (False, "Senior facilities engineer"),
    547: (False, "Reliability lead common services; 7+ yrs"),
    548: (False, "Staff SWE AI workload orchestration"),
    549: (False, "Senior SWE core open-source marimo"),
    550: (False, "Staff SWE developer experience"),
    551: (False, "Inventory control regional manager; ops"),
    552: (False, "HPC performance engineer; 5+ yrs"),
    553: (False, "Manager bare metal support engineering"),
    554: (False, "Sr SWE perf benchmarking; 5+ yrs"),
    555: (False, "Director engineering security products"),
    556: (False, "Senior security engineer enterprise"),
    557: (False, "Staff TPM cluster orchestration"),
    558: (True, "SWE inference AI/ML; IC1 level, mentorship, EC SWE role"),
    559: (False, "Director government affairs"),
    560: (False, "Solutions architect storage"),
    561: (False, "Security engineering manager network"),
    562: (False, "Data center security engineer; experienced"),
    563: (False, "Firmware engineering manager; leadership"),
    564: (False, "Staff security engineer SOAR; 8-10 yrs"),
    565: (False, "Data center energy analyst"),
    566: (False, "Principal engineer perf benchmarking; 10+ yrs"),
    567: (False, "Data center technician EOI; hardware ops not SWE"),
    568: (False, "Sr GPU infrastructure SWE; 5-8 yrs"),
    569: (False, "IT operations specialist Warsaw"),
    570: (False, "Senior managing associate general counsel"),
    571: (False, "Staff SWE inference"),
    572: (False, "Software enablement specialist; sales enablement"),
    573: (False, "Senior security engineer SOAR; 4-5 yrs"),
    574: (False, "SWE network services; 4+ yrs"),
    575: (False, "AV operations specialist"),
    576: (False, "Legal operations analyst"),
    577: (False, "Senior manager technical solutions manager"),
    578: (False, "Account executive M&E; sales"),
    579: (False, "Senior manager SOX business process"),
    580: (False, "Senior engineering manager data engineering"),
    581: (False, "Infrastructure community communications lead"),
    582: (False, "Senior threat intelligence specialist; 7+ yrs"),
    583: (False, "Senior counsel employment; legal"),
    584: (False, "Principal engineer cluster orchestration"),
    585: (False, "Senior supply materials manager"),
    586: (False, "Associate general counsel regulatory; legal"),
    587: (False, "Staff security engineer network security"),
    # --- Mistral AI (588-658) ---
    588: (False, "Applied AI FDE ML engineer Morocco; 2+ yrs IC"),
    589: (False, "Systems engineer HPC; experienced infra"),
    590: (False, "Engineering team lead DevEx; 5+ yrs lead"),
    591: (False, "AI deployment strategist Marseille; 2+ yrs consulting"),
    592: (False, "SAP platform lead; enterprise ERP"),
    593: (False, "Legal tech ops associate IP; 3+ yrs legal ops"),
    594: (False, "Legal counsel M&A; 7+ yrs legal"),
    595: (True, "Applied scientist/research engineer internship"),
    596: (False, "Code data annotation quality specialist; ops"),
    597: (False, "AI deployment strategist Marseille; 2+ yrs"),
    598: (False, "AI scientist audio; experienced research IC"),
    599: (False, "AI scientist Zurich; experienced research IC"),
    600: (False, "Data annotation quality specialist; ops"),
    601: (False, "Applied AI evaluation engineer; senior ML product"),
    602: (False, "Research engineer data infrastructure; 4+ yrs"),
    603: (False, "Partner marketing lead"),
    604: (False, "Social media specialist; marketing"),
    605: (False, "Applied AI FDE ML engineer Singapore; 2+ yrs"),
    606: (False, "AI developer advocate; 6+ yrs DevRel"),
    607: (False, "Datacenter hardware engineer HPC; experienced"),
    608: (False, "Applied AI technical lead FDE; 7/8+ yrs leadership"),
    609: (False, "AI scientist Palo Alto; experienced research IC"),
    610: (False, "Partner solution architect EMEA; presales"),
    611: (False, "Research operations manager; management"),
    612: (False, "Privacy legal counsel; legal"),
    613: (False, "Accounts payable manager; finance"),
    614: (False, "Product manager cloud partnerships; 7+ yrs PM"),
    615: (False, "Applied AI senior/staff fullstack Singapore; 5+ yrs"),
    616: (False, "AI scientist Warsaw; experienced research IC"),
    617: (False, "Account executive enterprise UK; 7-10 yrs sales"),
    618: (True, "Backend SWE NY; CS degree, no yrs bar, live-coding hire"),
    619: (False, "Research platform engineer; 5+ yrs DevOps/SRE"),
    620: (False, "AI scientist Paris/London; experienced research IC"),
    621: (False, "Lead accounting operations; finance"),
    622: (False, "TPM science operations code; management"),
    623: (False, "Applied science TPM EMEA; management"),
    624: (False, "Field hardware engineer HPC; experienced hardware"),
    625: (False, "Workplace ops Paris; facilities/ops"),
    626: (False, "Product designer Mistral cloud; design"),
    627: (False, "Product manager Forge; PM"),
    628: (False, "Research engineer data infrastructure; 4+ yrs"),
    629: (False, "AI deployment strategist Luxembourg; 2+ yrs consulting"),
    630: (False, "SWE enterprise agents; strong experience implied, no EC bar"),
    631: (False, "AI deployment strategist Singapore; 2+ yrs consulting"),
    632: (False, "Solutions architect partner EMEA; presales"),
    633: (False, "Applied AI technical lead FDE Montreal; leadership"),
    634: (False, "AI deployment strategist cybersecurity Paris; consulting"),
    635: (False, "Executive assistant to CRO; admin"),
    636: (False, "M&A tech engineer; experienced integrations"),
    637: (False, "AI deployment strategist Australia; 2+ yrs consulting"),
    638: (False, "Strategic partner lead SAP; partnerships"),
    639: (False, "Talent acquisition EMEA; recruiting"),
    640: (False, "Account executive enterprise France; sales"),
    641: (False, "Applied AI senior/staff DevOps SRE EMEA; 5+ yrs"),
    642: (False, "Founder in residence; founder program not EC hire"),
    643: (False, "Legal counsel banking/financing; legal"),
    644: (False, "Talent acquisition EMEA contractor; recruiting"),
    645: (False, "IFRS specialist; finance accounting"),
    646: (False, "Applied AI fullstack SWE sovereign Paris; 2+ yrs required"),
    647: (False, "Marketing programs manager"),
    648: (False, "Strategic partner lead OEM and neoclouds"),
    649: (False, "SWE QA; proven QA experience, no EC signal"),
    650: (False, "Technical marketing engineer solutions; marketing"),
    651: (False, "AI deployment strategist Seoul; 2+ yrs consulting"),
    652: (False, "Technical support engineer on-premise; support"),
    653: (False, "Enterprise sales leader"),
    654: (False, "Technical documentation manager; management"),
    655: (True, "Backend SWE Paris; CS degree, no yrs bar, live-coding hire"),
    656: (False, "Account executive enterprise NY; sales"),
    657: (False, "Lead documentation engineer; lead role"),
    658: (False, "Research SWE Paris/London; 4+ yrs distributed systems"),
}


def main() -> None:
    with open(BATCH, encoding="utf-8") as f:
        jobs = json.load(f)

    if len(jobs) != 659:
        raise SystemExit(f"Expected 659 jobs, got {len(jobs)}")

    missing = [i for i in range(len(jobs)) if i not in MANUAL]
    if missing:
        raise SystemExit(f"Missing manual labels for indices: {missing[:20]}... ({len(missing)} total)")

    labels = []
    inc = exc = 0
    with open(OUT, "w", encoding="utf-8") as out:
        for i, job in enumerate(jobs):
            include, reason = MANUAL[i]
            row = {
                "url": job["url"],
                "manual_include": include,
                "manual_reason": reason,
            }
            out.write(json.dumps(row, ensure_ascii=False) + "\n")
            labels.append(row)
            if include:
                inc += 1
            else:
                exc += 1

    print(f"Wrote {len(labels)} labels to {OUT.name}")
    print(f"INCLUDE: {inc}")
    print(f"EXCLUDE: {exc}")
    includes = [jobs[i]["title"] for i, r in enumerate(labels) if r["manual_include"]]
    print("Included titles:")
    for t in includes:
        print(f"  - {t}")


if __name__ == "__main__":
    main()
